### Get all languages
GET http://localhost:3000/api/languages

### Get all word pairs
GET http://localhost:3000/api/words

### Create word pair
POST http://localhost:3000/api/words
Content-Type: application/json

{
  "word1": "Dog",
  "language1_id": 2,
  "word2": "Koira",
  "language2_id": 1
}

### Delete word pair
DELETE http://localhost:3000/api/words/1

### Delete non-existing word pair
DELETE http://localhost:3000/api/words/999

### Try to delete word pair with invalid ID
DELETE http://localhost:3000/api/words/qwerty

### Update word pair
PUT http://localhost:3000/api/words/1
Content-Type: application/json

{
  "word1": "Cat",
  "word2": "Kissa"
}

### Fetch all tags
GET http://localhost:3000/api/tags

### Create new tag
POST http://localhost:3000/api/tags
Content-Type: application/json

{
  "name": "Animals"
}